# Generated by Django 3.1.4 on 2021-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201231_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='web_site',
            field=models.URLField(blank=True, max_length=64),
        ),
    ]
