version: '3.7'

services:
  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mps.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - mps/.env
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
