# Generated by Django 3.1.4 on 2021-02-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(choices=[('w', 'White'), ('b', 'Black'), ('wb', 'Both')], default='wb', max_length=32)),
                ('slug', models.SlugField(max_length=96, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('openings', models.ManyToManyField(related_name='tags', to='chess_openings.Opening')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('chapter_number', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField()),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='chess_openings.opening')),
            ],
            options={
                'ordering': ('chapter_number',),
            },
        ),
    ]
