# Generated by Django 3.1.4 on 2021-02-22 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chess_openings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opening',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='opening',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
