# Generated by Django 3.1.4 on 2021-02-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_openings', '0002_auto_20210222_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
