# Generated by Django 3.1.4 on 2021-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_openings', '0003_opening_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingchapter',
            name='url',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
