# Generated by Django 3.1.4 on 2021-01-12 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=12, max_length=255, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
