# Generated by Django 3.1.4 on 2021-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
