# Generated by Django 3.0.4 on 2020-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='url',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
