# Generated by Django 3.0.7 on 2020-12-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0002_auto_20201208_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmove',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess_db.ChessGame'),
        ),
    ]
