# Generated by Django 3.1.4 on 2021-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0004_auto_20210204_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmove',
            name='fen',
            field=models.CharField(max_length=128),
        ),
    ]
